/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_lognative_LogLib */

#ifndef _Included_com_intel_lognative_LogLib
#define _Included_com_intel_lognative_LogLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_lognative_LogLib
 * Method:    log
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_lognative_LogLib_log
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
